-- 중고 거래 게시물을 3건 이상 등록한 사용자
-- USER_ID, NICKNAME, 전체주소, 전화번호
-- USER_ID 내림차순

SELECT A.USER_ID, A.NICKNAME,
    CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTRING(A.TLNO, 1, 3), '-', SUBSTRING(A.TLNO, 4, 4), '-', SUBSTRING(A.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS A
JOIN (
    SELECT WRITER_ID, COUNT(*) AS ARTICLE_CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID HAVING ARTICLE_CNT >= 3
) AS B
ON A.USER_ID = B.WRITER_ID
ORDER BY A.USER_ID DESC;