SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM (
    SELECT C.YEAR, C.MONTH, C.GENDER, C.USER_ID, COUNT(*) AS COUNT
    FROM (
        SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER, A.USER_ID
        FROM ONLINE_SALE AS A
        JOIN USER_INFO AS B
        ON A.USER_ID = B.USER_ID
        HAVING B.GENDER IS NOT NULL
    ) AS C
    GROUP BY C.YEAR, C.MONTH, C.GENDER, C.USER_ID
) AS D
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;