-- 생산일자 2022년 5월
-- PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
-- TOTAL_SALES 내림차순, PRODUCT_ID 오름차순

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FO.TOTAL_AMOUNT * FP.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
) AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;