SELECT D.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT A.MEMBER_ID, A.REVIEW_TEXT, A.REVIEW_DATE
    FROM REST_REVIEW AS A
    JOIN (
        SELECT MEMBER_ID, COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT DESC
        LIMIT 1
    ) AS B
    ON A.MEMBER_ID = B.MEMBER_ID
) AS C
JOIN MEMBER_PROFILE AS D
ON C.MEMBER_ID = D.MEMBER_ID
ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT;