-- 22년 1월 도서 판매 데이터
-- 저자 별, 카테고리 별 판매량
-- 판매가 곱하기

-- 1월 저자별, 카테고리별 판매량
SELECT C.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, SUM(C.SUM_PRICE) AS TOTAL_SALES
FROM (
    -- 1월 BOOK_ID 별 판매 데이터
    SELECT A.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, A.SALES, B.PRICE, A.SALES * B.PRICE AS SUM_PRICE, A.SALES_DATE
    FROM BOOK_SALES AS A
    JOIN BOOK AS B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = DATE_FORMAT('2022-01-01', '%Y-%m')
) AS C
JOIN AUTHOR AS D
ON C.AUTHOR_ID = D.AUTHOR_ID
GROUP BY C.AUTHOR_ID, C.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
