-- 입양 간 동물 중 보호 기간이 가장 길었던 동물 두 마리
-- ID, NAME

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS AS A
JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(A.DATETIME, B.DATETIME) DESC
LIMIT 2;