-- 30일간의 대여 금액이 50만원 이상 200만원 미만
-- CAR_ID, CAR_TYPE, FEE
-- ORDER BY CARTYPE, CAR_ID DESC

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM (
    -- 자동차 종류가 '세단' 또는 'SUV'이면서 11월 1일 ~ 11월 30일 대여 가능한 차 정보
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM (
        -- 자동차 종류가 '세단' 또는 'SUV'
        SELECT * FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE LIKE '%세단%' OR CAR_TYPE LIKE '%SUV%'
    ) AS A
    LEFT JOIN (
        -- 11월 1일부터 11월 30일 사이에 대여 기록이 있는 CAR_ID
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= "2022-11-01" AND START_DATE <= "2022-11-30"
        GROUP BY CAR_ID
    ) AS B
    ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_ID IS NULL
) AS C
JOIN (
    -- 30일 이상 기준 세단, SUV 할인 플랜
    SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상' AND (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
) AS D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) >= 500000 AND ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;