-- 22년 5월 예약 조회
-- 진료과 코드별로 GROUP BY
-- 예약 건수 COUNT
SELECT MCDP_CD AS 진료과코드, COUNT(*) AS 5월예약건수
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = DATE_FORMAT('2022-05-01', '%Y-%m')
GROUP BY MCDP_CD
ORDER BY 5월예약건수, 진료과코드;
