SELECT J.FLAVOR
FROM
    -- 7월 아이스크림 총 주문량
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS J
JOIN
    -- 상반기 아이스크림 총 주문량
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS FIRST_HALF_TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR) AS F
ON J.FLAVOR = F.FLAVOR
ORDER BY J.JULY_TOTAL_ORDER + F.FIRST_HALF_TOTAL_ORDER DESC
LIMIT 3;