-- 조회수가 가장 높은 게시물
-- 첨부파일 경로
SELECT
    CONCAT('/home/grep/src/', B.BOARD_ID, '/',B.FILE_ID, B.FILE_NAME, B.FILE_EXT) AS FILE_PATH
FROM (
    SELECT *
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) AS A
JOIN USED_GOODS_FILE AS B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY B.FILE_ID DESC;